### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by Tsumitsuki** [bgauduch/call-of-duty-2-docker-server#70] opened 2021-06-01 15:18 UTC
looks like i have a simiilar issue like #1 

the docker just wont start wthis this log:

```
> [LIBCOD] Compiled for: CoD2 1.3
> [LIBCOD] Compiled Apr 15 2021 15:55:03 using GCC 8.3.0
> [PLUGIN LOADED]
CoD2 MP 1.3 build linux-i386 Jun 23 2006
----- FS_Startup -----
Current language: english
Current search path:
/root/.callofduty2/main
/home/cod2/main
/root/.callofduty2/raw
/root/.callofduty2/raw_shared
/root/.callofduty2/devraw
/root/.callofduty2/devraw_shared
/home/cod2/raw
/home/cod2/raw_shared
/home/cod2/devraw
/home/cod2/devraw_shared

File Handles:
----------------------
0 files in iwd files
ERROR: No languages available because no localized assets were found

Sys_Error: Error during initialization:

Couldn't load default_localize_mp.cfg. Make sure Call of Duty is run from the correct folder.

> [PLUGIN UNLOADED]
```

I'M on unRAID and my mounting looks like this:
![image](https://user-images.githubusercontent.com/32206990/120347853-ed142680-c2fc-11eb-8357-a508aab75ae2.png)

Docker Command:
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='cod2' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -v '/mnt/user/appdata/cod2server/main':'/home/cod2/main':'ro' 'bgauduch/cod2server'
edcd82f0dc56ea9214ed9b9f4dfa7aa836ecec67da41f2030cb944c0ead831bb

i guess i'm missing something obvious again. as usually^^

**Comment by bgauduch** [comment] 2021-06-02 12:39
Hello @Tsumitsuki and thanks for your interest in this project 👍 

I mostly support the provided docker-compose config for this project, but I'm not sure you are using the correct docker command to start the container.

You could try something more like this:
```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='cod2' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -v '/mnt/user/appdata/cod2server/main':'/home/cod2/main':'ro' 'bgauduch/cod2server'
```

> I'm not familiar with the `docker create` command, but it seem's like it will create the container but not start it.
    => "The docker create command creates a writeable container layer over the specified image and prepares it for running the specified command. The container ID is then printed to STDOUT. This is similar to docker run -d except the container is never started" - [source](https://docs.docker.com/engine/reference/commandline/create/)
    
If the issue is not resolved:
Looking at the server logs and config, it seems like the required games files are missing.

Could you please :
* ensure you correctly followed the [readme usage section](https://github.com/bgauduch/call-of-duty-2-docker-server#-usage)
* provide the full file list under the `/mnt/user/appdata/cod2server/main` path on your unRAID server

**Comment by Tsumitsuki** [comment] 2021-06-02 15:12
Hey. Thanks for the quick reply!

Haven't setup a docker via commands by now since unRAID provides a UI to do so.
Wich seems to be more difficult in some cases like this one. ¯\_(ツ)_/¯

I removed the docker and tried your command via promt.
The result seems to be the same:

`Couldn't load default_localize_mp.cfg. Make sure Call of Duty is run from the correct folder.

> [PLUGIN UNLOADED]
> [LIBCOD] Compiled for: CoD2 1.3
> [LIBCOD] Compiled Apr 15 2021 15:55:03 using GCC 8.3.0
> [PLUGIN LOADED]
CoD2 MP 1.3 build linux-i386 Jun 23 2006
----- FS_Startup -----
Current language: english
Current search path:
/root/.callofduty2/main
/home/cod2/main
/root/.callofduty2/raw
/root/.callofduty2/raw_shared
/root/.callofduty2/devraw
/root/.callofduty2/devraw_shared
/home/cod2/raw
/home/cod2/raw_shared
/home/cod2/devraw
/home/cod2/devraw_shared

File Handles:
----------------------
0 files in iwd files
ERROR: No languages available because no localized assets were found

Sys_Error: Error during initialization:`

Files inside of `/mnt/user/appdata/cod2server/main`:
![image](https://user-images.githubusercontent.com/32206990/120505440-447dc980-c3c5-11eb-875b-51dcc5aa8a34.png)

**Comment by bgauduch** [comment] 2021-06-17 14:31
Hello again @Tsumitsuki, sorry for the late answer !

It looks like the game files are not correctly mounted (or you have a docker volume misconfiguration) when starting the server.
Could you please provide the full docker command you used to start the cod2 server container ?

Another question, do you have the ability to run docker-compose on your unRAID machine ?
If you do, youo could try to use the supported compose file as describe [in the doc](https://github.com/bgauduch/call-of-duty-2-docker-server#launch-the-server) one you finish setting up the server following the [setup guide](https://github.com/bgauduch/call-of-duty-2-docker-server#launch-the-server).

**Comment by bgauduch** [comment] 2021-11-17 14:24
Hello again @Tsumitsuki !

I'm closing this issue now since I din't hear back from you.
Do not hesitate to comment back on this issue if you still get troubles !

Have a good day 😃

**Closed by bgauduch** 2021-11-17 14:24 UTC
Labels: bug
