### ISSUE TITLE
Container does not start

### ISSUE THREAD

**Issue by edi-design** [bgauduch/call-of-duty-2-docker-server#1] opened 2017-12-12 21:09 UTC
Hey,

i did everything documented in the README file but unfortunately it does not start.
Log says the following:

```
CoD2 MP 1.3 build linux-i386 Jun 23 2006
----- FS_Startup -----
Current language: english
Current search path:
/home/cod2/.callofduty2/main
/home/cod2/cod2server/main
/home/cod2/.callofduty2/raw
/home/cod2/.callofduty2/raw_shared
/home/cod2/.callofduty2/devraw
/home/cod2/.callofduty2/devraw_shared
/home/cod2/cod2server/raw
/home/cod2/cod2server/raw_shared
/home/cod2/cod2server/devraw
/home/cod2/cod2server/devraw_shared

File Handles:
----------------------
0 files in iwd files
ERROR: No languages available because no localized assets were found
Sys_Error: Error during initialization:
Couldn't load default_localize_mp.cfg.  Make sure Call of Duty is run from the correct folder.
```

It looks like it could not find the iwd files but they are all in the main folder.

```
➜  call-of-duty-2-docker-server (master) ✗ tree
.
├── LICENSE
├── README.md
├── backups
│   ├── cod2_lnxded_1_3
│   ├── cod2_lnxded_1_3_cracked
│   ├── cod2_lnxded_1_3_nodelay
│   ├── cod2_lnxded_1_3_nodelay_va_loc
│   ├── cod2_lnxded_1_3_patch_va_loc
│   └── gcc3-libs.tar.bz2
├── cod2server
│   ├── README.linux
│   ├── cod2_lnxded
│   └── main
│       ├── config.cfg
│       ├── iw_00.iwd
│       ├── iw_01.iwd
│       ├── iw_02.iwd
│       ├── iw_03.iwd
│       ├── iw_04.iwd
│       ├── iw_05.iwd
│       ├── iw_06.iwd
│       ├── iw_07.iwd
│       ├── iw_08.iwd
│       ├── iw_09.iwd
│       ├── iw_10.iwd
│       ├── iw_11.iwd
│       ├── iw_12.iwd
│       ├── iw_13.iwd
│       ├── iw_14.iwd
│       ├── iw_15.iwd
│       ├── localized_english_iw00.iwd
│       ├── localized_english_iw01.iwd
│       ├── localized_english_iw02.iwd
│       ├── localized_english_iw03.iwd
│       ├── localized_english_iw04.iwd
│       ├── localized_english_iw05.iwd
│       ├── localized_english_iw06.iwd
│       ├── localized_english_iw07.iwd
│       ├── localized_english_iw08.iwd
│       ├── localized_english_iw09.iwd
│       ├── localized_english_iw10.iwd
│       └── localized_english_iw11.iwd
└── docker
    └── dockerfile
```

I hope you can help me.

Thanks in advance.

Best regards,
André

**Comment by bgauduch** [comment] 2018-10-01 20:10
Hey Andre,

Well I somehow never had the notification about your issue, and just randomly saw it today, sorry about the delay (almost 1 year, I know...).

Well I was not able to reproduce this issue, and cannot really explain it without all the detailed steps you did :
* It might just be a docker version issue or something ?
* Or maybe a typo in the `docker run` command ?

So I just went ahead and updated the project a little bit, it should be working now using docker-compose :-)

Maybe it will be helpful to you, even after all this time. 

Best Regard,
Baptiste

**Comment by LSL1337** [comment] 2020-04-29 15:31
i have the same issue.
where should i find this file? It's not in my windows folder.

**Comment by bgauduch** [comment] 2020-04-29 16:18
Hello @LSL1337, thanks for reporting your issue !

Can you give me more contexte, logs and error messages about your issue ?
Is it related to game file (all the .iwd files) ?

**Comment by LSL1337** [comment] 2020-04-29 16:26
i see the following in the log:
> [LIBCOD] Compiled for: CoD2 1.3
> [LIBCOD] Compiled Apr 27 2020 17:08:28 using GCC 8.3.0
> [PLUGIN LOADED]
CoD2 MP 1.3 build linux-i386 Jun 23 2006
----- FS_Startup -----
Current language: english
Current search path:
/home/cod2/.callofduty2/main
/home/cod2/main
/home/cod2/.callofduty2/raw
/home/cod2/.callofduty2/raw_shared
/home/cod2/.callofduty2/devraw
/home/cod2/.callofduty2/devraw_shared
/home/cod2/raw
/home/cod2/raw_shared
/home/cod2/devraw
/home/cod2/devraw_shared

File Handles:
----------------------
0 files in iwd files
ERROR: No languages available because no localized assets were found

> [PLUGIN UNLOADED]
Sys_Error: Error during initialization:

Couldn't load default_localize_mp.cfg. Make sure Call of Duty is run from the correct folder.


I have my files in /home/cod2/main (all iwd) and the config file
in /home/cod2/ i have the localize.txt, and the linux ded server binary
i start the docker with +exec config.mp map_ratate, i get the above error.
where do I find that localize_mp.cfg? why can't it see my iwd files?

thanks for the fast response btw

**Comment by bgauduch** [comment] 2020-04-29 16:40
You are welcome @LSL1337 👍 
Thanks for the logs and detailed explanations.

From what I can understand, the `.iwd` files are missing inside the container. Maybe you forgot to configure the volume mount ?
 
Your docker command should be something like this:
```sh
docker container run -it -v /home/cod2/main:/home/cod2/main:ro -p 20500:20500/udp -p 20510:20510/udp -p 28960:28960/tcp -p 28960:28960/udp bgauduch/cod2server:latest +exec config.cfg
```

That being said, the easiest way to get started is to clone this repository and follow the [setup guide](https://github.com/bgauduch/call-of-duty-2-docker-server#setup-the-server), this way all the config is done in the docker-compose file and you just have to `docker-compose up -d` 😉

**Comment by LSL1337** [comment] 2020-04-29 17:46
I was mount home/cod2
I should have been mounting home/cod2/main to my main folder
it is working now.
how can I chose witch dedicated server file is used? i want to use the normal 1.3, not the cracked one

**Comment by bgauduch** [comment] 2020-04-29 18:59
@LSL1337 all good then !

To choose the dedicated server binary, you sadly have to do it manually for now (update Dockerfile, build the image and use it in the `docker container run`command).

I am currently working on setting up a CI to build multiple images for all server binaries, you can follow the progress on PR #36

**Comment by LSL1337** [comment] 2020-04-29 19:02
did you manage to enable punkbuster?, it is the last thing i need.
i ahe the latest files copied to the folder.
btw if i manually place a linux ded server file in the main cod folder, is it overwritten by the version in the docker?

thanks for the GREAT work with this docker. I haven't played this game in years. nice to be coming back and still finding servers. 15 years later a media server can run 10 cod2 servers :)

**Comment by bgauduch** [comment] 2020-04-30 07:46
Hello @LSL1337 , I never used PB before because almost everyone is playing on modified / cracked server today. I'm not sure it still supported, we should open a new issue regarding this so we can test 😉

You can actually place anything you want in the `main` folder on your computer (mods, etc), which is then mounted as a read-only volume by default.
That being said, this Docker image copy the cod2_lnxded binary on build : it is the one being use on server startup (you can see it in the `ENTRYPOINT` section of the Dockerfile)

Well thank you ! It is very fun to see people are still playing, and that this Docker image I created a long time ago is still being used 😃 
You can virtually run hundreds of cod2 server on today's hardware and network connection 😉

**Comment by bgauduch** [comment] 2020-04-30 07:46
closing this issue now as the subject has been resolved !

**Closed by bgauduch** 2020-04-30 07:46 UTC
Labels: bug
