### ISSUE TITLE
punkbuster is not activated

### ISSUE THREAD

**Issue by rodas007** [bgauduch/call-of-duty-2-docker-server#44] opened 2020-05-01 21:22 UTC
I'm trying to activate the punkbuster in the new version, but I don't activate it, it always tells me that it is 0, and I modified the file docker-compose.yaml :

"+set",
        "sv_punkbuster",
        "1",

and also in server_mp.conf :

set sv_punkbuster 1

But none of this works, am I doing something wrong?

**Comment by bgauduch** [comment] 2020-05-02 08:28
Hello @rodas007, thank you for opening this issue !

You did right, it should activate Punkbuster when `sv_punbkbuster`is set to 1.

I've just corrected some mistakes in the docker-compose setup, could you please test again after pulling the latest changes on master branch ?

Also I didn't release images before this morning. 
So if you were using another image tag than `latest`, punkbuster was not included yet. It is now : https://github.com/bgauduch/call-of-duty-2-docker-server/releases/tag/3.1.

If you still have the issue, can you provide me with the server logs when you run `docker-compose up` so we can investigate ?

**Comment by rodas007** [comment] 2020-05-03 08:53
hello, @bgauduch  the same thing happens to me as the user @fcakyon, the same report, with the latest build, now it won't start and it also tells me 0 iwd files, it seems to be a permission problem or something. , 

cod2_server_1  |
cod2_server_1  | > [PLUGIN UNLOADED]
cod2_server_1  | > [LIBCOD] Compiled for: CoD2 1.3
cod2_server_1  | > [LIBCOD] Compiled May  1 2020 17:50:17 using GCC 8.3.0
cod2_server_1  | > [PLUGIN LOADED]
cod2_server_1  | CoD2 MP 1.3 build linux-i386 Jun 23 2006
cod2_server_1  | ----- FS_Startup -----
cod2_server_1  | Current language: english
cod2_server_1  | Current search path:
cod2_server_1  | /home/cod2/.callofduty2/main
cod2_server_1  | /home/cod2/main
cod2_server_1  | /home/cod2/.callofduty2/raw
cod2_server_1  | /home/cod2/.callofduty2/raw_shared
cod2_server_1  | /home/cod2/.callofduty2/devraw
cod2_server_1  | /home/cod2/.callofduty2/devraw_shared
cod2_server_1  | /home/cod2/raw
cod2_server_1  | /home/cod2/raw_shared
cod2_server_1  | /home/cod2/devraw
cod2_server_1  | /home/cod2/devraw_shared
cod2_server_1  |
cod2_server_1  | File Handles:
cod2_server_1  | ----------------------
cod2_server_1  | 0 files in iwd files
cod2_server_1  | ERROR: No languages available because no localized assets were found
cod2_server_1  | Sys_Error: Error during initialization:
cod2_server_1  | Couldn't load default_localize_mp.cfg.  Make sure Call of Duty is run from the correct folder.

**Comment by bgauduch** [comment] 2020-05-03 08:59
Hello @rodas007 ! Thanks for the report, looks like the same issue indeed (#49)
After the discussion with @fcakyon yesterday I have pushed a small fix just now, could you test again with latest image please ?

Another question, was it working before ?

**Comment by rodas007** [comment] 2020-05-03 10:34
If before it worked perfectly, the server was working everything ok, now it doesn't work with the last build, the service is restarted all the time, I attach the log:
cod2_server_1 | errexit on
cod2_server_1 | noglob off
cod2_server_1 | ignoreeof off
cod2_server_1 | monitor off
cod2_server_1 | noexec off
cod2_server_1 | xtrace off
cod2_server_1 | verbose off
cod2_server_1 | noclobber off
cod2_server_1 | allexport off
cod2_server_1 | notify off
cod2_server_1 | nounset off
cod2_server_1 | saw off
cod2_server_1 | pipefail off
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw05.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_07.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_03.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw09.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_10.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_english_iw11.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw04.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_12.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw01.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw06.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/server_mp.cfg: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw02.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_09.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw00.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_15.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw11.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw07.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_01.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_02.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_11.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_04.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_00.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/punkbuster.cfg: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_06.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_13.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_14.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_08.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw10.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw08.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/iw_05.iwd: Read-only file system
cod2_server_1 | chown: /home/cod2/main/localized_spanish_iw03.iwd: Read-only file system
cod2_server_1 | chown: / home / cod2 / main: Read-only file system
cod2_server_1 | chown: / home / cod2 / main: Read-only file system
cod2server_cod2_server_1 exited with code 1

**Comment by bgauduch** [comment] 2020-05-04 07:21
Hello @rodas007, I'm sorrry to ear that, it is a regression then 😞 

I will try to spend some time on this issue this week, on the meantime could you try the fix from issue #49, especially from [this comment](https://github.com/bgauduch/call-of-duty-2-docker-server/issues/49#issuecomment-622943134) and [this one](https://github.com/bgauduch/call-of-duty-2-docker-server/issues/49#issuecomment-622940488) ?

**Comment by bgauduch** [comment] 2020-05-04 09:40
@rodas007 Closing this issue as punkbuster is working correctly, let's continu the issue tracking in #49

**Closed by bgauduch** 2020-05-04 09:40 UTC
Labels: bug
